### ISSUE TITLE
Wrong type assign to Sprintf in ante.go smartaccount

### ISSUE THREAD

**Issue by fibonacci998** [aura-nw/aura#133]
When viewing event smart_account_tx from this [tx](https://serenity.aurascan.io/transaction/D470B5F84BBC37BFBF74B96CD89A9A225B45D069735B59AD0C4CEE7F2152387A) on serenity, I got that value 
```
JSFzKFBBTklDPVN0cmluZyBtZXRob2Q6IHJlZmxlY3QuVmFsdWUuSW50ZXJmYWNlOiBjYW5ub3QgcmV0dXJuIHZhbHVlIG9idGFpbmVkIGZyb20gdW5leHBvcnRlZCBmaWVsZCBvciBtZXRob2QpLzI=
// decode base 64 return:
%!s(PANIC=String method: reflect.Value.Interface: cannot return value obtained from unexported field or method)/2
```
May be bug from this line: 
https://github.com/aura-nw/aura/blob/200f913b9982c4b4d78885938453c326372f4c83/x/smartaccount/ante.go#L385C97-L385C97

**Comment by Narutobacoshiba** [comment]
already fixed in commit [fix event attribute value](https://github.com/aura-nw/aura/commit/51ccfc4843c4967d59f807723e1edd269137d7e1)
